from .area import AreaAdmin
from .aula import AulaAdmin
from .cuerpo import CuerpoAdmin
from .laboratorio import LaboratorioAdmin
from .laboratorioInformatico import LaboratorioInformaticoAdmin
from .nivel import NivelAdmin
from .proyectorMultimedia import ProyectorMultimediaAdmin
from .tipoLaboratorio import TipoLaboratorioAdmin
from .visorTv import VisorTvAdmin
