from .area import AreaAdmin
from .aula import AulaAdmin
from .carruselImagenes import CarruselImagenes
from .cuerpo import CuerpoAdmin
from .imagenCarrusel import ImagenCarrusel
from .laboratorio import LaboratorioAdmin
from .laboratorioInformatico import LaboratorioInformaticoAdmin
from .nivel import NivelAdmin
from .recursoAli import RecursoAliAdmin
from .tipoLaboratorio import TipoLaboratorioAdmin
from .tipoRecursoAli import TipoRecursoAliAdmin
from .visorTv import VisorTvAdmin
