from django.conf.urls import url

from .views import (
    AreaDetailView,
    AulaDetailView,
    CuerpoDetailView,
    IndexView,
    LaboratorioElectronicaDetailView,
    LaboratorioElectronicaListView,
    LaboratorioInformaticoDetailView,
    LaboratorioInformaticoListView,
    NivelDetailView,
    ProyectorMultimediaDetailView,
    ProyectorMultimediaListView,
    recurso_eventos_json,
    SolicitudAulaView,
    SolicitudLaboratorioInformaticoView,
    SolicitudMaterialMultimediaView,
    TvBedeliaCuerposDetailView,
    TvBedeliaDetailView,
    TvCuerposListView,
)


urlpatterns = [
    url(
        r'^$',
        IndexView.as_view(),
        name='index'
    ),
    url(
        r'^cuerpo/(?P<numero>\d+)/$',
        CuerpoDetailView.as_view(),
        name='cuerpo_detalle'
    ),
    url(
        r'^cuerpo/(?P<numero_cuerpo>\d+)/nivel/(?P<numero_nivel>-?\d+)/$',
        NivelDetailView.as_view(),
        name='nivel_detalle'
    ),
    url(
        r'^aula/(?P<pk>\d+)/$',
        AulaDetailView.as_view(),
        name='aula_detalle'
    ),
    url(
        r'^area/(?P<slug>[-\w]+)/$',
        AreaDetailView.as_view(),
        name='area_detalle'
    ),
    url(
        r'^recurso/(?P<pk>\d+)/eventos/$',
        recurso_eventos_json,
        name='recurso_eventos_json'
    ),
    url(
        r'^laboratorios/electronica/$',
        LaboratorioElectronicaListView.as_view(),
        name='laboratorio_electronica_listado'
    ),
    url(
        r'^laboratorio/electronica/(?P<alias>[A-Za-z0-9]+)/$',
        LaboratorioElectronicaDetailView.as_view(),
        name='laboratorio_electronica_detalle'
    ),
    url(
        r'^laboratorios/informatica/$',
        LaboratorioInformaticoListView.as_view(),
        name='laboratorio_informatico_listado'
    ),
    url(
        r'^laboratorio/informatica/(?P<alias>[A-Za-z0-9]+)/$',
        LaboratorioInformaticoDetailView.as_view(),
        name='laboratorio_informatico_detalle'
    ),
    url(
        r'^proyectores/$',
        ProyectorMultimediaListView.as_view(),
        name='proyector_multimedia_listado'
    ),
    url(
        r'^proyector/(?P<identificador>[A-Za-z0-9_-]+)/$',
        ProyectorMultimediaDetailView.as_view(),
        name='proyector_multimedia_detalle'
    ),
    url(
        r'^solicitud/aula/$',
        SolicitudAulaView.as_view(),
        name='solicitud_aula'
    ),
    url(
        r'^solicitud/laboratorio/informatica/$',
        SolicitudLaboratorioInformaticoView.as_view(),
        name='solicitud_laboratorio_informatico'
    ),
    url(
        r'^solicitud/material_multimedia/$',
        SolicitudMaterialMultimediaView.as_view(),
        name='solicitud_material_multimedia'
    ),
    url(
        r'^tv/cuerpos/$',
        TvCuerposListView.as_view(),
        name='tv_cuerpos'
    ),
    url(
        r'^tv/bedelia/(?P<area_slug>[-\w]+)/$',
        TvBedeliaDetailView.as_view(),
        name='tv_area'
    ),
    url(
        r'^tv/bedelia/(?P<area_slug>[-\w]+)/cuerpos/$',
        TvBedeliaCuerposDetailView.as_view(),
        name='tv_area_cuerpos'
    ),
]
